# Generated by Django 5.0 on 2023-12-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timerApp', '0002_timer_greeting_delete_speech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='greeting',
            new_name='speech',
        ),
    ]
